// Sourced exclusively from the "Quotes" section of Yi's connected Google Doc.
export const dailyQuotes = [
  "Du gjør meg så glad.\n You make me so happy.",
  "Hver dag og hvert øyeblikk vi kommer hjem til hverandre er en påminnelse om hvor dyrebart dette livet er.\n Every day and every moment that we come home to each other is a reminder of how precious this life is.",
  "Jeg tenkte at romantikk bare kunne være til hinder på veien. Det ville sannsynligvis vært sant med hvem som helst jeg noensinne hadde møtt, unntatt deg.\n I thought romance could only be a hindrance on the path, which was probably true had it been with anyone else I'd ever met.",
  "Jeg kunne forklart det med karma og dharma i stedet for tilfeldigheter: at vi to ble ansatt på samme kaffebar.\n An improbability I'd explain with karma and dharma rather than coincidence: you and I getting hired at the same coffee shop.",
  "«Jeg kunne forelske meg i denne kvinnen.»\n \"I could fall in love with this woman.\"",
  "Jeg har aldri møtt noen som passer så perfekt til å gå ved siden av meg gjennom dette livet.\n I'd never met anyone so perfectly suited for me to walk alongside in this life.",
  "Du er det minst dømmende mennesket jeg noensinne har møtt.\n You are the least judgmental person towards others that I have ever met.",
  "Du søker ansvar før du skylder på andre.\n You seek responsibility before blaming anyone else.",
  "Selv om du er utrolig intelligent, klamrer du deg aldri til synspunktene dine som de eneste gyldige. Det er en egenskap som blir sjeldnere for hver dag.\n Despite being incredibly intelligent, you never cling to your perspectives as being the only valid ones, a trait that seems rarer every day.",
  "Du er intuitiv der jeg er overrasjonell, organisert der jeg er kaotisk.\n You are intuitive where I am over-rational, organized where I am chaotic.",
  "Du ser gjennom sosiale konvensjoner og finner sannheten med ditt eget kompass.\n You see through social convention and can find truth with your own compass.",
  "Når tankene mine drar meg i alle retninger unntatt hit, ser jeg nysgjerrigheten og den rene, glade tilstedeværelsen din når du tar en bit av noe godt eller finner en fin snøflak, og jeg ser hvor mye jeg har å lære av deg.\n When my mind pulls me in every direction except for being here, I watch your curiosity and pure joyful presence [...] and I see how much I have to learn from you.",
  "Gleden din hver gang jeg klipper meg eller kommer hjem fra jobb varmer meg helt inn til kjernen.\n Your excitement every time I get a haircut or come home from work warms me to my core.",
  "Folk sier at du er en engel. Men en engel kan i beste fall peke en vei. For meg har du blitt veien.\n People tell me they see you as an angel, yet an angel can, at best, point one on a path. For me, you have become the path.",
  "Jeg får se et tynnere slør av tvil avsløre et enormt reservoar av kreativ energi i deg, og det er vakkert. Du er vakker.\n I get to watch a thinning veil of doubt increasingly reveal a vast reservoir of creative energy in you, and it is beautiful. You are beautiful.",
  "Hver eneste av dine gode egenskaper ville vært nok til å gjøre deg eksepsjonell. Sammen gjør de deg urealistisk overlegen, som en katt.\n Any of your positive qualities would be enough to make you elite, and combined, make you unrealistically overpowered, like a cat.",
  "Du har tålmodig stått ved min side gjennom alt slags vær, selv når det gjorde vondt.\n You have patiently stood by me through all the weather, even when it hurt to do so.",
  "Uansett hvilken tilstand jeg er i, blokkert, anspent, ute av balanse, for stiv eller for løs, i ferd med å gå i oppløsning eller druknende i min egen melodrama, møter du meg som en klippe, med visdom og tålmodighet. Du krever ingenting, bare venter, og når jeg endelig kommer opp for å puste, er du der, bak de øynene, klar til å leke.\n No matter what state I am in, you meet me as a rock with wisdom and patience. Demanding nothing, just waiting [...] ready to play.",
  "Jeg føler meg så trygg og fri sammen med deg.\n I feel so safe and free with you.",
  "Min åndelige søken ga meg fred før jeg møtte deg, men én blind flekk hindret meg i å gå rett. Nå vet jeg at det var et hull i form av deg.\n My spiritual seeking provided peace before I met you, but one blind spot had kept me from walking straight, and I know it now to have been a hole in the shape of you.",
  "En sann og full harmoni mellom sinn, kropp og sjel, der alle lag av selvet er oppfylt i enighet. Det er retning.\n A true and full alignment of Mind, Body and Soul, with all layers of the self fulfilled unanimously. That is direction.",
  "Min dharma er blitt åpenbart for meg som en middelvei i form av dette ekteskapet: mellom ytterpunktene avholdenhet og overflod, med risiko og disiplin, eventyr og måtehold, lidenskap og stillhet. Jeg har aldri sett en kjærlighet så sunn.\n My Dharma has been revealed to me as a middle path in the form of this marriage [...] I have never seen a love so sane.",
  "Du er alteret jeg tilber gjennom. Avataren jeg ber til.\n You are the altar through which I worship. The avatar to whom I pray.",
  "Jeg lover å holde, og ikke klamre.\n I vow to hold, and not cling.",
  "Jeg lover å fortsette å pusse meg selv som et speil, slik at du blir minnet om din sanne skjønnhet, helt til du ikke trenger noe speil for å vite den.\n I vow to keep polishing myself as a mirror so that you are reminded of your true beauty until no mirror will be required for you to know it.",
  "Jeg lover aldri å slutte å arbeide for å bli mannen du fortjener å være sammen med. Og å leke, og krangle, og overgi meg. Og å akseptere at jeg ikke alltid kan være perfekt.\n I promise to never stop working towards becoming the man that you deserve to be with. And playing, and fighting, and surrendering. And accepting that I can't always be perfect.",
  "Jeg lover aldri å miste av syne hvor heldig jeg er som får være sammen med deg.\n I promise to never lose sight of how lucky I am to be with you.",
  "Jeg gleder meg så mye til å tilbringe resten av livet med deg. Men jeg har et enda større løfte å gi i dag: å nære en kjærlighet som er som et bål i øyeblikket, der fortiden og fremtiden bare er papirark kastet på ilden.\n I'm so excited to spend the rest of my life with you, yet there is a greater commitment I intend to make today [...] the past and future are but sheets of paper tossed in.",
  "Jeg lover å alltid elske deg, her og nå. Med dette åndedraget. Og dette. Og dette.\n I promise to always love you, here and now. With this breath. And this one. And this one.",
  "Dette øyeblikket er det eneste stedet livet faktisk skjer.",
  "Du trenger ikke løse hele livet nå. Bare dette åndedraget.",
  "Tankene dine er været. Du er himmelen.",
  "Legg merke til at du legger merke til. Der begynner friheten.",
  "Fortiden er en historie, fremtiden er en gjetning. Nå er det eneste som er ekte.",
  "Stillhet er ikke tomhet. Det er rommet alt annet vokser i.",
  "Når du lytter helt, forsvinner halve problemet.",
  "Du er mer enn historien du forteller om deg selv.",
  "Det du motstår, blir sittende. Det du møter med vennlighet, kan slippe taket.",
  "Ikke alt trenger å bli forstått. Noe trenger bare å bli følt.",
  "Kjærlighet begynner der behovet for å ha rett slutter.",
  "Vi er alle på vei hjem, bare på ulike stier.",
  "Å gi uten å regne er den enkleste formen for frihet.",
  "Du blir det du gjør gjentatte ganger, ikke det du gjør en gang med stor innsats.",
  "Gjør det så lite at du ikke kan si nei.",
  "Hver handling er en stemme på personen du vil bli.",
  "Ikke vent på motivasjon. Start, så kommer den etter.",
  "Bedre systemer slår sterkere viljestyrke.",
  "Én prosent bedre hver dag blir til et helt annet liv på et år.",
  "Miljøet ditt vinner over gode intensjoner. Gjør det gode enkelt.",
  "«Ennå» er det viktigste ordet i språket. Jeg kan det ikke ennå.",
  "Feil er ikke dommer. De er data.",
  "Innsats er ikke et tegn på svakhet, men på at du vokser.",
  "Du er ikke ferdig. Det er den beste nyheten du kan få.",
  "Utfordringer er treningsrommet for hjernen din.",
  "Nysgjerrighet er sterkere enn selvtillit.",
  "Å huske at livet er skjørt gjør hver dag kostbar.",
  "Ingenting er permanent, og det er grunnen til at alt er verdt å sette pris på.",
  "Møt avskjeder med takk, ikke bare med sorg.",
  "Et fredfullt sinn er den beste gaven du kan ta med deg gjennom livet.",
  "Medfølelse er ikke å ta bort andres smerte, men å sitte med dem i den.",
  "Det viktigste du etterlater, er hvordan folk følte seg rundt deg.",
  "Usikkerhet er ikke problemet. Kampen mot den er.",
  "Du kan ikke holde på elven. Du kan bare lære å flyte.",
  "Det å ikke vite er der alt nytt begynner.",
  "Livet er en dans, ikke en reise med et mål.",
  "Slipp kontrollen, og du oppdager hva som bærer deg.",
  "Sikkerhet er en illusjon. Mot er å leve likevel.",
  "«Sinnet er alt. Det du tenker, blir du.» (Buddha, tilskrevet)",
  "«Hat avtar aldri ved hat, bare ved kjærlighet.» (Dhammapada)",
  "«Du har makt over ditt eget sinn, ikke over hendelsene utenfra. Innse dette, og du finner styrke.» (Marcus Aurelius, fritt gjengitt)",
  "«Hindringen på veien blir veien.» (Marcus Aurelius, fritt gjengitt)",
  "«Vi lider oftere i fantasien enn i virkeligheten.» (Seneca)",
  "«En reise på tusen mil begynner med ett skritt.» (Lao Tzu)",
  "«Den som kjenner andre er klok. Den som kjenner seg selv er opplyst.» (Lao Tzu)",
  "«Når jeg slutter å være den jeg er, blir jeg den jeg kan bli.» (Lao Tzu, fritt gjengitt)",
  "«Såret er stedet lyset kommer inn.» (Rumi, fritt gjengitt)",
  "«Det du søker, søker etter deg.» (Rumi, fritt gjengitt)",
  "«Det som ligger bak oss og foran oss, er små ting sammenlignet med det som ligger inni oss.» (Emerson, tilskrevet)",
  "«Ingenting stort er noen gang oppnådd uten begeistring.» (Emerson)",
  "«Jeg gikk inn i skogen fordi jeg ville leve bevisst.» (Thoreau, fritt gjengitt)",
  "«Vi bør aldri la noe ubrukt gå tapt: dagen i dag er alt vi eier.» (Seneca, fritt gjengitt)",
  "Jeg er trygg i kroppen min og rolig i sinnet.",
  "Jeg velger ro fremfor hastverk.",
  "Jeg har det jeg trenger for å ta neste steg.",
  "Jeg tillater meg å hvile uten dårlig samvittighet.",
  "Jeg er verdifull uten å prestere.",
  "Jeg slipper det jeg ikke kan kontrollere.",
  "Jeg snakker vennlig til meg selv i dag.",
  "Jeg er takknemlig for det små og det store.",
  "Gjør én ting om gangen, og gjør den hel.",
  "Hvile er en del av arbeidet, ikke en belønning for det.",
  "Si nei til det gode for å si ja til det viktige.",
  "Begynn dagen med ro, ikke med skjermen.",
  "Du trenger ikke en perfekt plan. Du trenger et første skritt.",
  "Gå en tur. De fleste problemer ser annerledes ut utendørs.",
  "Søvn, vann, bevegelse, vennlighet. Det grunnleggende bærer det meste.",
  "Fremgang er ofte stille. Stol på det som ikke synes ennå.",
  "Planlegg pauser like seriøst som møter.",
  "Slutt dagen med tre ting du er takknemlig for.",
] as const;
